### PR TITLE
Added datatable component. Comments for how to use are in BrowseReportsView.vue

### PR DESCRIPTION
**Pull request by blakegood31**

### CODE REVIEW

**Review by leathalman — APPROVED** [review]
Looks good to me! For your sake, I hope the datatable.css changes were not by hand - that looks like quite the process.

**Comment by carsonlfreeman** [comment]
Looks good to me I trust our frontend wizard

**Review by carsonlfreeman — APPROVED** [review]
Looks good to me I trust our front end wizard :D

**Review by Zhelus — APPROVED** [review]
Nice work standing all this up!

**Pull request merged**
